### ISSUE TITLE
RDS or H5AD file in https://anglohlabs.shinyapps.io/blood_devcell_shiny/

### ISSUE THREAD

**Issue by Counts-Xin** [lohlaboratory/blood-differentiation#1]
Perfect work, can you share your RDS or H5AD file in https://anglohlabs.shinyapps.io/blood_devcell_shiny/ with us, so that we can better use your data?

**Comment by lohlaboratory** [comment]
Thank you for your question! The .h5 files are available here: [https://www.dropbox.com/scl/fo/zd7w3zvgbevtljbeg7ol4/ABqBmjv1O5UuR6CXFbIaB3I?rlkey=vj7a2pucp52z6afltyv1vlis2&st=pjckwg50&dl=0](url)

**Comment by Counts-Xin** [comment]
It appears that the file is missing from this link.

**Comment by Counts-Xin** [comment]
Thank you so much!

**Comment by Counts-Xin** [comment]
The matrix that appears to have been downloaded from your link - is the expression matrix. If possible, could you graciously share the Seurat or Scanpy object featured in your Figure 5G, inclusive of the UMAP embedding? So that we can directly use your data and cite your paper. I appreciate your assistance, thank you very much!

**Comment by sherrylizheng** [comment]
We have updated the [Dropbox link](https://www.dropbox.com/scl/fo/zd7w3zvgbevtljbeg7ol4/ABqBmjv1O5UuR6CXFbIaB3I?rlkey=vj7a2pucp52z6afltyv1vlis2&st=pjckwg50&dl=0) to include the requested Seurat object. This link and a brief description of folder contents is now available in the [main branch](https://github.com/lohlaboratory/blood-differentiation). Hope this helps!

**Comment by Counts-Xin** [comment]
Thank you so much!
